[[monitor-infrastructure-and-hosts]]
= Analyze infrastructure and host metrics

In the {infrastructure-app}, you can visualize infrastructure
metrics to help diagnose problematic spikes, identify high resource utilization,
automatically discover and track pods, and unify your metrics with logs and APM
data in {es}.

Using {agent} integrations, you can ingest and analyze metrics from servers,
Docker containers, Kubernetes orchestrations, explore and analyze application
telemetry, and more.

To analyze infrastructure and host metrics, go to the **Observability** UI.
Find **Infrastructure** in the main menu or use the <<kibana-navigation-search,global search field>>.

The {infrastructure-app} provides a few different views of your data.

[cols="1,1"]
|===
| **Inventory**
|Provides a metrics-driven view of your entire infrastructure grouped by the resources that you are monitoring.

<<view-infrastructure-metrics,Learn more about the Inventory page > >>

| **Metrics Explorer**
| Enables you to create time-series visualizations based on aggregation of your metrics, chart them against related metrics, and break them down per the field of your choice.

<<explore-metrics,Learn more about the Metrics Explorer > >>

| **Hosts**
| Provides a metrics-driven view of your infrastructure backed by an easy-to-use interface called Lens.

<<analyze-hosts,Learn more about the Hosts page > >>

|===

By default, the {infrastructure-app} displays metrics from {es} indices that
match the `metrics-*` and `metricbeat-*` index patterns. To learn how to change
this behavior, refer to <<configure-settings>>.

To learn more about the metrics shown in the {infrastructure-app}, refer to
the <<metrics-reference>> documentation.
